# notificaciones-producer/src/main/resources/application.properties
quarkus.http.port=8080

mp.messaging.outgoing.eventos-educativos-out.connector=smallrye-kafka
mp.messaging.outgoing.eventos-educativos-out.topic=eventos-educativos
mp.messaging.outgoing.eventos-educativos-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.eventos-educativos-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer

kafka.bootstrap.servers=localhost:9092

%dev.quarkus.kafka.devservices.enabled=false
%dev.quarkus.kafka.devservices.topic-partitions.eventos-educativos=3