# notificaciones-consumer/src/main/resources/application.properties
quarkus.http.port=8081

kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.historial-in.connector=smallrye-kafka
mp.messaging.incoming.historial-in.topic=eventos-educativos
mp.messaging.incoming.historial-in.group.id=historial-group
mp.messaging.incoming.historial-in.value.deserializer=io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
mp.messaging.incoming.historial-in.mp.messaging.deserializer.value.type=ar.edu.unlp.info.consumer.model.EventoEducativo
mp.messaging.incoming.historial-in.auto.offset.reset=earliest

mp.messaging.incoming.alertas-in.connector=smallrye-kafka
mp.messaging.incoming.alertas-in.topic=eventos-educativos
mp.messaging.incoming.alertas-in.group.id=alertas-group
mp.messaging.incoming.alertas-in.value.deserializer=io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
mp.messaging.incoming.alertas-in.mp.messaging.deserializer.value.type=ar.edu.unlp.info.consumer.model.EventoEducativo
mp.messaging.incoming.alertas-in.auto.offset.reset=earliest

mp.messaging.incoming.certificados-in.connector=smallrye-kafka
mp.messaging.incoming.certificados-in.topic=eventos-educativos
mp.messaging.incoming.certificados-in.group.id=certificados-group
mp.messaging.incoming.certificados-in.value.deserializer=io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
mp.messaging.incoming.certificados-in.mp.messaging.deserializer.value.type=ar.edu.unlp.info.consumer.model.EventoEducativo
mp.messaging.incoming.certificados-in.auto.offset.reset=earliest

mp.messaging.outgoing.alertas-docentes-out.connector=smallrye-kafka
mp.messaging.outgoing.alertas-docentes-out.topic=alertas-docentes
mp.messaging.outgoing.alertas-docentes-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.eventos-fallidos-out.connector=smallrye-kafka
mp.messaging.outgoing.eventos-fallidos-out.topic=eventos-fallidos
mp.messaging.outgoing.eventos-fallidos-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=notificaciones

%dev.quarkus.kafka.devservices.enabled=true
%dev.quarkus.mongodb.devservices.enabled=true