%dev.quarkus.mongodb.devservices.port=27018
# --- Configuración GLOBAL (Aplica a Dev y Test) ---
quarkus.mongodb.database=repositorio_academico

# --- Apagar temporalmente Hibernate ORM (Postgres) si no lo estás usando ---
# Esto evita que Quarkus tire error al iniciar si tenés la dependencia en el pom.xml
quarkus.hibernate-orm.enabled=false
quarkus.hibernate-reactive.enabled=false